### PR TITLE
Use docker user namespacing

### PR DESCRIPTION
**Pull request by toolmantim**
Rebases #32 against master and removes the old permission fix hook.

See #32 for details on the what, why and caveats

### CODE REVIEW

**Comment by toolmantim** [comment]
@lox @Vektah I'm going to give this a spin in prod today…

**Comment by Vektah** [comment]
I think there are issues with uid > 1 at the moment. It's currently fine
for the root user inside the container but any other accounts don't get
squashed.

**Comment by lox** [comment]
Yup, came here to say the same as @Vektah, think it would be sensible to keep the permissions resetting stuff.

**Comment by toolmantim** [comment]
What if we reinstate the permissions hook, add a boolean to an “Experimental Features” section of the CF parameters to turn this on?

Is there a fix for the user problem you mention? :|

**Comment by lox** [comment]
Sounds good to me @toolmantim. I'll leave it up to @Vektah to explain the issue, I roughly understand it, but whether it's a bug or an unexpected side-effect of the uid mapping I'm not sure of.

**Comment by Vektah** [comment]
This stackoverflow has a decent description of the issue
http://stackoverflow.com/questions/35291520/docker-and-userns-remap-how-to-manage-volume-permissions-to-share-data-betwee

Basically I thought that userns could 'squash' the user IDs in the
container to a single one on the host, but it only lets you apply and
offset and limit. The way it's currently set its offsetting so root =
buildkite-agent and limit =1 but as soon as anything runs as a non root
user in a container it dies.

This means it's good as a security feature but not a great fit for this use.

**Comment by Vektah** [comment]
I think a complete solution would involve some filesystem acls to force
uid/gid + userns to give security from the underlying container.
On 17 May 2016 6:11 PM, "Adam Scarr" <adam@vektah.net> wrote:

This stackoverflow has a decent description of the issue
http://stackoverflow.com/questions/35291520/docker-and-userns-remap-how-to-manage-volume-permissions-to-share-data-betwee

Basically I thought that userns could 'squash' the user IDs in the
container to a single one on the host, but it only lets you apply and
offset and limit. The way it's currently set its offsetting so root =
buildkite-agent and limit =1 but as soon as anything runs as a non root
user in a container it dies.

This means it's good as a security feature but not a great fit for this use.

**Comment by toolmantim** [comment]
Hmm… sounds like it's good to add for security purposes then, but then still have the fix permissions script. And we can make it the default? (no need for a parameter)

**Comment by lox** [comment]
I'd say we can eventually, I'm just worried about what undiscovered issues there are.

**Comment by toolmantim** [comment]
Ok… so how about we keep the fix permissions and put what's here behind a "Experimental Features" parameter group for testing?

**Comment by Vektah** [comment]
I think to do this for security purposes you would want to bump the uid and gid start ranges up, otherwise they will collide with other users. For example if you had user id = 2 in the container any files it writes will be created as uid = 500 on the host (buildkite-agent = 498 + 2)

Or use `--userns-remap="default"` and let docker create a throw away user, which would be the same thing.

I don't think its usable without some filesystem level squashing though.

**Comment by lox** [comment]
Yeah, I think `--userns-remap=default` is probably the best way forward, there are too many other question marks for me with mapping into an existing range. Then we just flatten permissions after commands run via the current sudo approach.

**Comment by lox** [comment]
Although then we need a way for the container to read the stuff owned by buildkite-agent. Blargh.

Docs here btw https://docs.docker.com/engine/reference/commandline/daemon/#daemon-user-namespace-options

**Comment by lox** [comment]
Perhaps we could just generate a `/etc/subuid/etc/subuid with the root user mapped to `buildkite-agent` and then the a whole lot of entries for subsequent users with high, throwaway UID's?

**Comment by lox** [comment]
The other major gotcha with this is that `--privileged` wont be supported.

**Comment by Vektah** [comment]
Could use http://bindfs.org --force-user

**Comment by toolmantim** [comment]
I think we should just close this for now, until we're ready to give it a stab again

**Pull request closed without merging**
